name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [master, main]
    paths-ignore: ['*.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          
          # Sửa lỗi copy file
          find . -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds \;
          
          # Copy an toàn plugins.json
          [ -f build/plugins.json ] && cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          git add .
          
          # Chỉ commit nếu có thay đổi
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Build ${GITHUB_SHA:0:7} - $(date +'%Y-%m-%d %H:%M')"
            git push origin builds --force
          fi
