# Tên của workflow
name: Sync Build Artifacts from Repo A

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
on:
  # Kích hoạt workflow này khi một workflow khác hoàn thành
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
  
      - name: Checkout Repo B
        uses: actions/checkout@v4

     
      - name: Clean old artifacts
        run: |
      - name: Checkout Repo A builds branch
        uses: actions/checkout@v4
        with:
          repository: 'tuangayxx/Gayvn'
          ref: 'builds'
          path: '.repo-a-builds'

      - name: Copy new artifacts
        run: |
          echo "Copying new build files..."
          rsync -av --delete .repo-a-builds/ .

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          
          if ! git diff --staged --quiet; then
            git commit -m "Sync: Update build artifacts from Repo A (${{ github.event.workflow_run.head_sha }})"
            git push
          else
            echo "No changes to commit."
          fi
