name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [master, main]
    paths-ignore: ['*.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
          run: |
      cd $GITHUB_WORKSPACE/src
      chmod +x gradlew
      ./gradlew make makePluginsJson --info --console=verbose
      find . -name "*.cs3" -exec cp --parents {} $GITHUB_WORKSPACE/builds \;
      find . -name "plugins.json" -exec cp --parents {} $GITHUB_WORKSPACE/builds \;
